// Code generated by Slice Machine. DO NOT EDIT.

import Hero from "./Hero";
import LogoCloud from "./LogoCloud";
import SponsorGrid from "./SponsorGrid";

export { Hero, LogoCloud, SponsorGrid };

export const components = {
  hero: Hero,
  logo_cloud: LogoCloud,
  sponsor_grid: SponsorGrid,
};
