// Code generated by Slice Machine. DO NOT EDIT.

import ContentShowcase from './ContentShowcase';
import Hero from './Hero';
import LogoCloud from './LogoCloud';
import SponsorGrid from './SponsorGrid';

export {
	ContentShowcase,
	Hero,
	LogoCloud,
	SponsorGrid,
};

export const components = {
	content_showcase: ContentShowcase,
	hero: Hero,
	logo_cloud: LogoCloud,
	sponsor_grid: SponsorGrid,
};
